# SPROUTCORE CONFIGURATION FILE
# Use this file to customize the URLs, source and output paths and and other
# options used by the SproutCore build system to create the output for your
# SproutCore applications.

# If you want to use the libraries provided by other gems, require those gems
# here.  SproutCore will automatically locate and load any bundles found in
# your load path.  The sproutcore gem is automatically loaded for you.
#
# require: ['sproutcore','another_gem']

# This configuration section will be applied to all bundles used by your
# application, even bundles that come from other gems.

############################################################################
# GLOBAL CONFIG
# 
# These options will apply to ALL bundles that are built unless they are 
# overridden by a specific bundle.
#
all:
  
  # Name the default set of languages you want to build for your projects.  
  # Unless you specify the language on the command line for sc-build, all
  # languages you specify here will be built.
  build_languages: [en, fr, de, ja, es, it]

  # Name any other frameworks your bundles depend upon.  The stylesheets and
  # JavaScript for required bundles will be loaded before your bundle on your
  # page.
  required: [sproutcore, common_assets]
  
  # This string will be prepended before any URLs that reference JavaScript,
  # CSS or images in your files.
  resources_at: static
  
  # This string will be prepended before any index.html urls that actually
  # load your clients.  Setting this to an empty string will mount all
  # of your clients at the root URL level.
  index_at: ''

  # If you also need to load external stylesheets not managed by the bundle
  # system, name the URLs you want to reference here.
  #
  #stylesheet_libs: [/stylesheets/public.css]

  # If you also need to load external javascripts not managed by the bundle
  # system, name the URLs you want to reference here.  These will be loaded
  # automatically.
  #
  #javascript_libs: [/javascript/scriptaculous.js] 

  # This is the preferred language.  When the user visits the root URL of
  # your client, this is the language they will get.  When looking for a
  # resource (such as an image or stylesheet), SproutCore will also try
  # your preferred language .lproj if it cannot find the resource in the
  # current language.
  #
  #preferred_language: fr

  # If you want to use a default root layout template other than the default
  # provided by SproutCore, you can specifiy the path name to the index.html
  # here.  If you provide a relative path, SproutCore will assume the file
  # is relative to the root of this project.
  #
  #layout: sproutcore:lib/index.rhtml

  # This is the fully qualified path to the directory you want all of your
  # static files stored in.  You can place any files not managed by the build
  # system here.  SproutCore will also save its cached resources here.
  #
  #public_root: PROJECT_ROOT:public

  # The default build mode.  Normally you can specify this on the command
  # line as well using the -e option, but you can override the default
  # using this config as well.
  #
  #build_mode: production
  #############################################################################
# BUNDLE CONFIGS
# 
# These options apply only to the named bundles.  Use this section to
# override global settings that differ.
#

config(common_assets):
  required: sproutcore

#############################################################################
# PROXY SETTINGS
# 
# You can proxy certain URLs to another backend system.  Just configure the 
# proxy setting here.  In your key, identify the URL root for the proxy, 
# then name the host, optional port, protocol, and a different URL base if 
# necessary
#
proxy(/statuses):
  to: twitter.com
